### ISSUE TITLE
Permission to use and adapt code

### ISSUE THREAD

**Issue by LMB25** [asadTariq666/BPM-Alpha-Attribute-Selection#1]
Dear Tariq,
I'm currently working on my master's thesis in which I'm conducting a case study in the area of comparative process mining. My research design is based on the PCM and P²CM. When comparing instances, your VPC is particularly helpful in incorporating the stochastic perspective. :) Therefore, I would like to ask for your permission to use and adapt the code for the VPC in my master's thesis. If that would be all right, would it be possible for you to add an open-source license to the repository?
Thanks and best regards,
Lina

**Comment by asadTariq666** [comment]
Hi Lina,
You may use the repository for your research. :)
